version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  test:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run:
          command: yarn run build:demo
          name: Run YARN build
workflows:
  test_my_app:
    jobs:
      - test
